# Generated by Django 5.2.13 on 2026-04-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_profile_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
