# Generated by Django 5.2.13 on 2026-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_course_slug_alter_mastercategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
