# Generated by Django 6.0.3 on 2026-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_profile_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes_file',
            field=models.FileField(blank=True, help_text='Upload PDF Notes for this lesson', max_length=500, null=True, upload_to='lesson_notes/'),
        ),
    ]
