# Generated by Django 5.2.13 on 2026-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_lesson_content_file_alter_lesson_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.CharField(blank=True, help_text='Use relative link like /course/python-course/', max_length=500),
        ),
    ]
