# Generated by Django 6.0.3 on 2026-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_pendingregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, help_text='Link to a course or page'),
        ),
    ]
